<?xml version="1.0"?>
<package format="3">
  <name>static_tf_publisher</name>
  <version>0.1.0</version>
  <description>Publish static TF transforms from ROS 2 parameters</description>
  <maintainer email="jfrascon@gmail.com">Juan Francisco Rascon Crespo</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>

  <exec_depend>builtin_interfaces</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>ros2_launch_helpers</exec_depend>
  <exec_depend>tf2_ros</exec_depend>

  <test_depend>ament_cmake_lint_cmake</test_depend>
  <test_depend>ament_cmake_xmllint</test_depend>
  <test_depend>ament_cmake_flake8</test_depend>
  <test_depend>ament_cmake_pep257</test_depend>
  <!--
  <test_depend>ament_cmake_copyright</test_depend>
  -->
  <!--
  <test_depend>ament_cmake_mypy</test_depend>
  -->
  <test_depend>ament_cmake_pytest</test_depend>
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_index_python</test_depend>
  <test_depend>ros2launch</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
